---
services:
  mongo:
    image: "mongo:8.0.15"
    ports:
      - "27017:27017"
    user: "1000:1000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db/mongo:/data/db
  redis:
    image: "redis:8.2.2"
    user: "1000:1000"
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data
  postgres:
    image: "postgres:17.6"
    user: "1000:1000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: root
    ports: 
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
